name: challenge
on:
  push:
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Run the single catching test
        run: >
          dotnet test MoreLinq.Test/MoreLinq.Test.csproj
          -c Release
          -f net8.0
          --filter "FullyQualifiedName~AtLeastTest.AtLeast"
